[project]
name = "ignite"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "einops>=0.8.1",
    "numpy>=2.2.6",
    "pytest>=9.0.1",
    "pytorch-lightning>=2.5.6",
    "torch>=2.9.1",
    "tqdm>=4.67.1",
]
