defaults:
  - model: llama_debug # models: [deepseek, llama]
  - tokenizer: gpt2 # tokenizers: [gpt2, llama3]
  - hparams: debug
  - _self_

seed: 0
ckpt_path: "ember/llm/checkpoints"
push_to_hf_hub: false